export const CONFIG = {
  EMOTE_CHAR_CAP: 2000,
  KINDROID_TOTAL_CHAR_CAP: 4000,
  VOICE_MATCH_THRESHOLD: 0.7,
  FACE_MATCH_THRESHOLD: 0.7,
  VOICE_ENROLLMENT_SAMPLES: 3,
  AUDIOSNAP_DURATION_SEC: 5,
  PULSE_INTERVAL_MINUTES: 15,
  BAROMETER_ALERT_THRESHOLD_HPA: 4.0,
  RIDE_G_THRESHOLD: 2.5,
  WEATHER_RESEND_INTERVAL_MIN: 30,
  GEMINI_MAX_RETRIES: 3,
  GEMINI_RETRY_BASE_MS: 2000,
} as const;
