#!/usr/bin/env bash
# Runs on EAS build machines after `npm install`, before `expo prebuild`.
#
# 1. Ensures hermesc and any other linux64-bin executables have +x.
#    npm installs often strip exec bits on Linux for some prebuilt
#    binaries, which makes Gradle's `createBundleReleaseJsAndAssets`
#    fail with "A problem occurred starting process '.../hermesc'".
#
# 2. Regenerates services/geminiPrompt.generated.ts from the markdown
#    source — equivalent to the local preandroid / prestart npm hooks.

set -e

echo "[eas-post-install] populating hermes-compiler stub with real hermesc binaries..."
# RN 0.82's generated android/app/build.gradle hardcodes
# `hermesCommand = <hermes-compiler path>/hermesc/%OS-BIN%/hermesc`. The
# npm package `hermes-compiler` (listed as a dep by react-native) is a
# stub at version 0.0.0 — package.json only, no binaries. The actual
# hermesc binaries live at node_modules/react-native/sdks/hermesc/.
# Mirror them into the stub's expected location so the hardcoded path
# works without patching build.gradle (which gets regenerated by prebuild).
HERMES_SRC="node_modules/react-native/sdks/hermesc"
HERMES_DST="node_modules/hermes-compiler/hermesc"
if [ -d "$HERMES_SRC" ] && [ -d "node_modules/hermes-compiler" ]; then
  mkdir -p "$HERMES_DST"
  # Copy every OS-specific bin directory that exists in the source
  for osbin in linux64-bin osx-bin win64-bin; do
    if [ -d "$HERMES_SRC/$osbin" ]; then
      cp -r "$HERMES_SRC/$osbin" "$HERMES_DST/"
      echo "[eas-post-install] copied $osbin"
    fi
  done
else
  echo "[eas-post-install] WARN: hermesc source or stub missing — skipping"
fi

echo "[eas-post-install] fixing exec bits on linux binaries..."
find node_modules -type f -path "*/linux64-bin/*" -exec chmod +x {} + 2>/dev/null || true
find node_modules -type f -name "hermesc" -exec chmod +x {} + 2>/dev/null || true
find node_modules -type f -name "hbcdump" -exec chmod +x {} + 2>/dev/null || true

echo "[eas-post-install] regenerating Gemini system prompt..."
node scripts/build-prompt.mjs

echo "[eas-post-install] done."
